import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { normalizeTechStack } from "@/lib/utils";
import { canUseCli } from "@/lib/access";
import crypto from "crypto";

export async function GET(req: Request) {
  const url = new URL(req.url);
  const apiKey = req.headers.get("x-api-key") || url.searchParams.get("apiKey");
  const workspaceId = url.searchParams.get("workspace");

  if (!apiKey?.startsWith("xynn_live_")) {
    return NextResponse.json({ error: "Invalid API key" }, { status: 401 });
  }
  if (!workspaceId) {
    return NextResponse.json({ error: "Missing workspace id" }, { status: 400 });
  }

  const hash = crypto.createHash("sha256").update(apiKey).digest("hex");

  const apiKeyRecord = await prisma.apiKey.findUnique({
    where: { keyHash: hash },
    include: { user: { include: { subscription: true } } },
  });

  if (!apiKeyRecord) {
    return NextResponse.json({ error: "Invalid API key" }, { status: 401 });
  }

  const sub = apiKeyRecord.user.subscription;

  // Paywall guard: CLI Sync hanya untuk Starter & Pro (PRD §3.4).
  if (!canUseCli(sub)) {
    return NextResponse.json(
      { error: "Payment required. Upgrade to STARTER/PRO to use CLI Sync." },
      { status: 402 }
    );
  }

  const workspace = await prisma.workspace.findFirst({
    where: { id: workspaceId, userId: apiKeyRecord.userId },
  });

  if (!workspace) {
    return NextResponse.json({ error: "Workspace not found" }, { status: 404 });
  }

  const techStackArray = normalizeTechStack(workspace.techStack);

  const cursorRules = [
    `# .cursorrules generated by XynnPrototype`,
    `# Workspace: ${workspace.title}`,
    `# Tech Stack: ${techStackArray.join(", ")}`,
    ``,
    `You are an expert developer working on "${workspace.title}".`,
    workspace.description || "",
    ``,
    "Always refer to PRD.md for full specifications.",
  ].join("\n");

  return NextResponse.json({
    prd: workspace.fullPrdMd || `# ${workspace.title}\n\nPRD belum di-generate.`,
    cursorRules,
    title: workspace.title,
    techStack: techStackArray,
  });
}
