// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Shadow DB dipakai `prisma migrate dev` untuk replay migrasi.
    // Tanpa baris ini, Prisma 7 (config-file mode) mengabaikan
    // SHADOW_DATABASE_URL di .env dan mencoba memakai database kerja,
    // sehingga `migrate dev` gagal dengan P3006 ("already exists").
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
